### PR TITLE
Add embed type settings to the embed button form and config entity export

### PR DESCRIPTION
**Pull request by davereid**

### CODE REVIEW

**Comment by davereid** [comment]
GIF of the form in action now

anim

**Comment by davereid** [comment]
@cs-shadow Mind taking a look over this?

**Comment by davereid** [comment]
Companion branch in entity_embed based on this work: https://github.com/drupal-media/entity_embed/compare/use-embed-api-button-config

> 287 additions and 1,070 deletions

:smile:

**Comment by cs-shadow** [comment]
@davereid Sorry I couldn't look at it earlier but this looks pretty great. Big ups

**Pull request merged**
